apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oncall.fullname" . }}-mongodb-data
  namespace: {{ include "oncall.namespace" . }}
  labels:
    {{- include "oncall.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mongodb.storage.storageClassName }}
  storageClassName: {{ .Values.mongodb.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
