{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oncall.fullname" . }}-frontend
  namespace: {{ include "oncall.namespace" . }}
  labels:
    {{- include "oncall.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "oncall.selectorLabels" (dict "name" "frontend" "release" .Release.Name) | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.frontend.service.targetPort }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "oncall.selectorLabels" (dict "name" "mongodb" "release" .Release.Name) | nindent 14 }}
      ports:
        - port: 27017
    - to:
        - podSelector:
            matchLabels:
              {{- include "oncall.selectorLabels" (dict "name" "calculator" "release" .Release.Name) | nindent 14 }}
      ports:
        - port: {{ .Values.calculator.service.targetPort }}
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oncall.fullname" . }}-calculator
  namespace: {{ include "oncall.namespace" . }}
  labels:
    {{- include "oncall.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "oncall.selectorLabels" (dict "name" "calculator" "release" .Release.Name) | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "oncall.selectorLabels" (dict "name" "frontend" "release" .Release.Name) | nindent 14 }}
      ports:
        - port: {{ .Values.calculator.service.targetPort }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "oncall.selectorLabels" (dict "name" "mongodb" "release" .Release.Name) | nindent 14 }}
      ports:
        - port: 27017
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oncall.fullname" . }}-mongodb
  namespace: {{ include "oncall.namespace" . }}
  labels:
    {{- include "oncall.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "oncall.selectorLabels" (dict "name" "mongodb" "release" .Release.Name) | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "oncall.selectorLabels" (dict "name" "frontend" "release" .Release.Name) | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "oncall.selectorLabels" (dict "name" "calculator" "release" .Release.Name) | nindent 14 }}
      ports:
        - port: 27017
{{- end }}
