apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oncall.fullname" . }}-secrets
  namespace: {{ include "oncall.namespace" . }}
  labels:
    {{- include "oncall.labels" . | nindent 4 }}
type: Opaque
data:
  flask-secret-key: {{ .Values.frontend.env.secretKey | b64enc | quote }}
